---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- spec/
- "public/assets/application-658ad0b54ea49b046d9385b1af3b90e79cf0dc212298fafc84e59d85d006e1b0.js"
- "app/assets/javascripts/d3-timeline.js"
- "app/assets/javascripts/d3-timeline-events.js"
