languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "app/assets/javascripts/d3-timeline.js"
- "app/assets/javascripts/d3-timeline-events.js"
- "app/vendor"
- "app/public/assets/application-658ad0b54ea49b046d9385b1af3b90e79cf0dc212298fafc84e59d85d006e1b0.js
- "app/spec"
- "app/db"
