# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b7bb757f946a08219e15c6420fca84baefe501d7eb6a2f9298baab1d88f86b2f600942b35b6e66f0d52027b38256e9430bb38515af4f6db4dcf4369b301d1fa

test:
  secret_key_base: c1d6345a67a5b08f96876fc33d2f424a2f201ce30f32ab07838f4c11aa88a5c8e7ce02d6193a0ebbc076ee9e1850865758581fbae63d020810dc18cd815ac4c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
